name: Build Windows Launcher

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine64 wine32

      - name: Package Windows app
        run: |
          npx electron-packager . "Seven Launcher" \
            --platform=win32 \
            --arch=x64 \
            --out=release \
            --overwrite \
            --app-version=${{ github.ref_name }} \
            --build-version=${{ github.ref_name }} \
            --icon=assets/icon.ico
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload packaged app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-launcher
          path: release/Seven\ Launcher-win32-x64/**
