name: Build Windows Launcher

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build unpacked dir for Windows
        run: npx electron-builder --win dir --x64 --ia32
        env:
          CSC_LINK: ''
          CSC_KEY_PASSWORD: ''

      - name: Upload unpacked directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-launcher
          path: dist/win-unpacked/**
