name: Build Windows Launcher

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Windows ZIP
        run: npx electron-builder --win zip --x64
        # electron-builder détecte automatiquement le bon exécutable sur Windows

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-launcher
          path: dist/*.zip
